#!/usr/bin/env bash
set -euo pipefail

readonly brew_install_url="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
readonly script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly brew_prefix_linux="/home/linuxbrew/.linuxbrew"
readonly fonts_dir="$HOME/.local/share/fonts"
readonly fzf_dir="$HOME/.fzf"
readonly nvm_dir="$HOME/.nvm"
readonly nvim_dir="/opt/nvim-linux-x86_64"
readonly profile_dir="$HOME/.profile.d"
readonly profile_path_file="$profile_dir/dotfiles-path.sh"
readonly tpm_dir="$HOME/.local/share/tmux/plugins/tpm"
readonly nerd_font_name="${NERD_FONT_NAME:-JetBrainsMono}"

log() {
  printf '\n==> %s\n' "$*"
}

warn() {
  printf 'WARN: %s\n' "$*" >&2
}

fatal() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fatal "Required command not found: $1"
}

ensure_not_root() {
  if [ "$(id -u)" -eq 0 ]; then
    fatal "Do not run this script with sudo or as root. Run ./setup.sh as your normal user; it will ask for sudo when needed."
  fi
}

find_homebrew() {
  local prefix

  if command -v brew >/dev/null 2>&1; then
    command -v brew
    return 0
  fi

  for prefix in "$brew_prefix_linux" "$HOME/.linuxbrew" /opt/homebrew; do
    if [ -x "$prefix/bin/brew" ]; then
      printf '%s\n' "$prefix/bin/brew"
      return 0
    fi
  done

  return 1
}

ensure_sudo_ready_for_homebrew() {
  if [ "$(uname -s)" != "Linux" ] || [ "$(id -u)" -eq 0 ]; then
    return
  fi

  if sudo -n true 2>/dev/null; then
    return
  fi

  log "Homebrew's Linux installer may need sudo to create $brew_prefix_linux"
  sudo -v
}

install_homebrew() {
  local installer status

  installer="$(mktemp)"

  log "Downloading Homebrew installer"
  curl -fL "$brew_install_url" -o "$installer"

  ensure_sudo_ready_for_homebrew

  log "Running Homebrew installer"
  status=0
  NONINTERACTIVE=1 /bin/bash "$installer" || status=$?
  rm -f "$installer"
  return "$status"
}

ensure_repo() {
  local repo_url="$1"
  local dest_dir="$2"

  if [ -d "$dest_dir/.git" ]; then
    log "Updating $(basename "$dest_dir")"
    git -C "$dest_dir" pull --ff-only
    return
  fi

  log "Cloning $(basename "$dest_dir")"
  git clone --depth 1 "$repo_url" "$dest_dir"
}

append_once() {
  local file="$1"
  local line="$2"

  touch "$file"
  if ! grep -Fxq "$line" "$file"; then
    printf '\n%s\n' "$line" >> "$file"
  fi
}

ensure_homebrew() {
  local brew_bin=""

  if brew_bin="$(find_homebrew)"; then
    eval "$("$brew_bin" shellenv)"
    log "Using Homebrew at $(brew --prefix)"
    return
  fi

  log "Installing Homebrew"
  install_homebrew

  brew_bin="$(find_homebrew)" || fatal "Homebrew installation failed"
  eval "$("$brew_bin" shellenv)"
  log "Using Homebrew at $(brew --prefix)"
}

configure_shell_paths() {
  log "Configuring shell PATH"
  mkdir -p "$profile_dir"

  cat > "$profile_path_file" <<EOF
# Generated by dotfiles setup.sh.
for brew_bin in /home/linuxbrew/.linuxbrew/bin/brew "\$HOME/.linuxbrew/bin/brew" /opt/homebrew/bin/brew; do
  if [ -x "\$brew_bin" ]; then
    eval "\$("\$brew_bin" shellenv)"
    break
  fi
done

export PATH="\$HOME/bin:\$HOME/.local/bin:/usr/local/bin:\$PATH"
if [ -d "$nvim_dir/bin" ]; then
  export PATH="\$PATH:$nvim_dir/bin"
fi
EOF

  append_once "$HOME/.profile" '[ -f "$HOME/.profile.d/dotfiles-path.sh" ] && . "$HOME/.profile.d/dotfiles-path.sh"'
  append_once "$HOME/.bashrc" '[ -f "$HOME/.profile.d/dotfiles-path.sh" ] && . "$HOME/.profile.d/dotfiles-path.sh"'
  append_once "$HOME/.zprofile" '[ -f "$HOME/.profile.d/dotfiles-path.sh" ] && . "$HOME/.profile.d/dotfiles-path.sh"'
  if [ -f "$HOME/.zshrc" ]; then
    append_once "$HOME/.zshrc" '[ -f "$HOME/.profile.d/dotfiles-path.sh" ] && . "$HOME/.profile.d/dotfiles-path.sh"'
  fi
}

remove_apt_packages() {
  local package removable_packages=()

  if [ "$(uname -s)" != "Linux" ] || ! command -v dpkg-query >/dev/null 2>&1 || ! command -v apt-get >/dev/null 2>&1; then
    return
  fi

  for package in "$@"; do
    if dpkg-query -W -f='${db:Status-Abbrev}' "$package" 2>/dev/null | grep -q '^ii '; then
      removable_packages+=("$package")
    fi
  done

  if [ "${#removable_packages[@]}" -eq 0 ]; then
    return
  fi

  log "Removing apt-managed copies: ${removable_packages[*]}"
  sudo env DEBIAN_FRONTEND=noninteractive apt-get remove -y "${removable_packages[@]}"
}

remove_non_brew_packages() {
  remove_apt_packages \
    stow \
    ripgrep \
    fd-find \
    tmux \
    starship \
    zoxide \
    lazygit \
    zsh \
    yq \
    git-delta \
    xdotool \
    wmctrl
}

brew_install() {
  local package missing_packages=()

  log "Updating Homebrew"
  NONINTERACTIVE=1 CI=1 brew update

  for package in "$@"; do
    if brew list --formula --versions "$package" >/dev/null 2>&1; then
      log "$package already installed"
      continue
    fi

    missing_packages+=("$package")
  done

  if [ "${#missing_packages[@]}" -eq 0 ]; then
    return
  fi

  log "Installing Homebrew packages: ${missing_packages[*]}"
  NONINTERACTIVE=1 CI=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install "${missing_packages[@]}"
}

brew_upgrade() {
  log "Upgrading managed Homebrew packages"
  NONINTERACTIVE=1 CI=1 HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade "$@"
}

install_brew_packages() {
  local packages=(
    stow \
    ripgrep \
    fd \
    tmux \
    starship \
    zoxide \
    lazygit \
    zsh \
    unzip \
    python \
    yq \
    git-delta \
    fontconfig \
    xdotool \
    wmctrl
  )

  brew_install "${packages[@]}"
  brew_upgrade "${packages[@]}"
}

install_nerd_font() {
  log "Installing JetBrainsMono Nerd Font"
  mkdir -p "$fonts_dir"

  local release_tag font_zip
  release_tag="$(curl -fsSL https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest | sed -n 's/.*"tag_name": "\([^"]*\)".*/\1/p' | head -n1)"
  [ -n "$release_tag" ] || fatal "Unable to determine the latest Nerd Fonts release"

  font_zip="$fonts_dir/${nerd_font_name}.zip"
  curl -fL "https://github.com/ryanoasis/nerd-fonts/releases/download/${release_tag}/${nerd_font_name}.zip" -o "$font_zip"
  unzip -o "$font_zip" -d "$fonts_dir"
  rm -f "$font_zip"

  if command -v fc-cache >/dev/null 2>&1; then
    fc-cache -fv "$fonts_dir"
  else
    warn "fc-cache not found; refresh font caches after logging in again"
  fi
}

install_fzf() {
  ensure_repo https://github.com/junegunn/fzf.git "$fzf_dir"
  "$fzf_dir/install" --all --no-update-rc
}

install_tpm() {
  mkdir -p "$(dirname "$tpm_dir")"
  ensure_repo https://github.com/tmux-plugins/tpm "$tpm_dir"

  log "Installing tmux plugins"
  XDG_CONFIG_HOME="$script_dir/tmux/.config" TMUX_PLUGIN_MANAGER_PATH="$(dirname "$tpm_dir")" "$tpm_dir/bin/install_plugins"
}

install_nvim() {
  log "Installing Neovim"

  local asset_name tmp_tar
  case "$(uname -m)" in
    x86_64|amd64)
      asset_name="nvim-linux-x86_64.tar.gz"
      ;;
    aarch64|arm64)
      asset_name="nvim-linux-arm64.tar.gz"
      ;;
    *)
      fatal "Unsupported architecture for Neovim: $(uname -m)"
      ;;
  esac

  tmp_tar="$(mktemp)"
  curl -fL "https://github.com/neovim/neovim/releases/latest/download/${asset_name}" -o "$tmp_tar"
  sudo rm -rf "$nvim_dir"
  sudo tar -C /opt -xzf "$tmp_tar"
  export PATH="$PATH:$nvim_dir/bin"
  rm -f "$tmp_tar"
}

install_nvm_and_node() {
  export NVM_DIR="$nvm_dir"

  if [ ! -s "$NVM_DIR/nvm.sh" ]; then
    log "Installing nvm"
  else
    log "Updating nvm"
  fi
  PROFILE=/dev/null bash -c "$(curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh)"

  # shellcheck disable=SC1090
  . "$NVM_DIR/nvm.sh"

  log "Installing Node.js LTS"
  nvm install --lts
  nvm alias default 'lts/*'
}

install_npm_tools() {
  if ! command -v npm >/dev/null 2>&1; then
    fatal "npm not found after nvm installation"
  fi

  log "Installing Node.js language-server helpers"
  npm install -g \
    css-variables-language-server \
    typescript \
    typescript-language-server \
    vscode-langservers-extracted \
    @microsoft/compose-language-service \
    @tailwindcss/language-server
}

ensure_zsh_path() {
  if [ -x /bin/zsh ]; then
    return
  fi

  local zsh_path=""
  if command -v zsh >/dev/null 2>&1; then
    zsh_path="$(command -v zsh)"
  else
    zsh_path="$(brew --prefix zsh)/bin/zsh"
  fi

  [ -x "$zsh_path" ] || fatal "zsh was not installed correctly"

  log "Linking /bin/zsh to $zsh_path for tmux"
  sudo ln -sf "$zsh_path" /bin/zsh
}

prompt_default_shell() {
  local answer current_shell zsh_path

  if ! command -v chsh >/dev/null 2>&1; then
    warn "chsh not found; skipping default shell setup"
    return
  fi

  zsh_path="$(command -v zsh || true)"
  if [ -z "$zsh_path" ] || [ ! -x "$zsh_path" ]; then
    warn "zsh not found; skipping default shell setup"
    return
  fi

  current_shell="$(getent passwd "${USER:-$(id -un)}" | cut -d: -f7)"
  current_shell="${current_shell:-unknown}"
  if [ "$current_shell" = "$zsh_path" ]; then
    log "Default shell is already $zsh_path"
    return
  fi

  printf '\nMake %s your default login shell? [y/N] ' "$zsh_path"
  read -r answer
  case "$answer" in
    [Yy]|[Yy][Ee][Ss])
      if ! grep -Fxq "$zsh_path" /etc/shells; then
        log "Adding $zsh_path to /etc/shells"
        printf '%s\n' "$zsh_path" | sudo tee -a /etc/shells >/dev/null
      fi

      log "Changing default shell to $zsh_path"
      chsh -s "$zsh_path"
      ;;
    *)
      log "Keeping current default shell: $current_shell"
      ;;
  esac
}

print_status() {
  printf '\n==> Install status\n'
  printf '  %-30s %s\n' "stow" "$(command -v stow >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "ripgrep" "$(command -v rg >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "fd" "$(command -v fd >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "JetBrainsMono font" "$(ls "$fonts_dir"/*"${nerd_font_name}"* >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "fzf" "$([ -d "$fzf_dir" ] && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "tpm" "$([ -d "$tpm_dir" ] && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "tmux" "$(command -v tmux >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "starship" "$(command -v starship >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "zoxide" "$(command -v zoxide >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "lazygit" "$(command -v lazygit >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "nvim" "$([ -x "$nvim_dir/bin/nvim" ] && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "nvm" "$([ -s "$NVM_DIR/nvm.sh" ] && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "node" "$(command -v node >/dev/null 2>&1 && echo OK || echo MISSING)"
  printf '  %-30s %s\n' "npm packages" "$(command -v npm >/dev/null 2>&1 && npm list -g typescript-language-server >/dev/null 2>&1 && echo OK || echo MISSING)"
}

main() {
  ensure_not_root

  need_cmd curl
  need_cmd file
  need_cmd git
  need_cmd tar
  need_cmd sudo

  ensure_homebrew
  remove_non_brew_packages
  install_brew_packages
  ensure_zsh_path
  install_nerd_font
  install_fzf
  install_tpm
  install_nvim
  configure_shell_paths
  install_nvm_and_node
  install_npm_tools
  print_status
  prompt_default_shell
}

main "$@"
